# Generated by Django 5.0.6 on 2024-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_crime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='advogado',
            new_name='nomeAdvogado',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='nome',
            new_name='nomeCliente',
        ),
        migrations.AddField(
            model_name='processo',
            name='cpfCliente',
            field=models.CharField(default='', max_length=11),
        ),
    ]
