# Generated by Django 5.0.6 on 2024-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos_crime', '0002_rename_advogado_processo_nomeadvogado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='descricao',
            new_name='descricaoCaso',
        ),
    ]
