# Generated by Django 5.0.6 on 2024-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_crime', '0004_rename_cpfcliente_processo_cpfexecutado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=100),
        ),
    ]
